name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: [enhancement]
projects: ["Watts-Lab/12"]
body:
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Please fill in the user story for this feature request. If appropriate, you can provide multiple user stories.
      placeholder: "As a [type of user], I want [an action] so that [a benefit/a reason]."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe the feature you'd like. A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: What would this feature enable?
      description: Explain what this feature would enable researchers to do that they can't do with the existing syntax or structure of the platform.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Required for existing experiments
        - Enables new types of experiments
        - Convenience for researchers
        - Convenience for developers
        - Good hygiene
